# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - bottom_holder_rotation
      - shoulder_arm_rotation
      - arm_holder_right_after_shoulder_rotation
      - elbow_arm_rotation
      - gripper_holder_rotation
      - end_factor_rotation
